# Generated by Django 3.2.9 on 2022-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('projectName', models.AutoField(primary_key=True, serialize=False)),
                ('developerNames', models.CharField(max_length=1000)),
                ('dateOfStart', models.DateField(max_length=1000)),
                ('dateOfEnd', models.DateField(max_length=1000)),
                ('languagesUsed', models.CharField(max_length=1000)),
                ('projectContent', models.CharField(max_length=1000)),
            ],
        ),
    ]
